services:
  mysql:
    image: mysql:8.0
    container_name: mysql-laravel
    environment:
  
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: erp_orders
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: always

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
